version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    volumes:
      - ./db_data:/var/lib/postgresql/data

  app:
    container_name: 'node'
    build: .
    user: node
    working_dir: '/home/node/workspace'
    environment:
      - WATCHPACK_POLLING=true
    tty: true
    volumes:
      - ../workspace:/home/node/workspace
    depends_on:
      - postgres
